Updated README.md
SymbiFlow/yosys-symbiflow-plugins pull request #111
Opened 2021-05-28 08:14 UTC by mkurc-ant

Signed-off-by: Maciej Kurc <mkurc@antmicro.com>

2021-05-28 08:20 UTC, mkurc-ant commented
@lnsharma @tpagarani FYI

2021-05-28 16:58 UTC, mithro requested changes
Please update the commit message to reflect information about what is being changed.

Better name would be; `Adding information about QLF FPGA plugin to README.md`

2021-06-01 13:25 UTC, mkurc-ant commented
@mithro Done.

2021-06-01 13:41 UTC, mithro approved these changes

2021-06-01 13:41 UTC, merged