Add uhdm-plugin
SymbiFlow/yosys-symbiflow-plugins pull request #141
Opened 2021-10-29 07:29 UTC by kamilrakoczy

This PR adds uhdm-plugin that allows to read UHDM and parse it to yosys AST.

2021-11-05 11:43 UTC, tgorochowik approved these changes

2021-11-05 15:08 UTC, mkurc-ant requested changes
Please update the top-level `README.md` and include there a very brief description of what the plugin is and what it does followed by a list of Yosys passes it includes.

Otherwise LGTM

2021-11-08 08:16 UTC, kamilrakoczy commented
@mkurc-ant I've updated ``README.md`` file and added information about UHDM plugin.

2021-11-08 09:00 UTC, acomodi approved these changes
LGTM

2021-11-08 09:02 UTC, merged