add support for k6n10 factor family
SymbiFlow/yosys-symbiflow-plugins pull request #150
Opened 2021-11-22 09:45 UTC by tpagarani

Added support for K6N10 family with soft adder carry chain and True Dual Port BRAM
Signed-off-by: Tarachand Pagarani <tpagarani@quicklogic.com>

2021-11-22 09:46 UTC, tpagarani commented
@kgugala, @mkurc-ant please review and merge this PR

2021-11-22 13:57 UTC, mkurc-ant requested changes
Some changes requested.

2021-11-22 13:57 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/lut_map.v
> +/*     generate
This module as a techmap does not have much sense as with the block commented-out it won't have any desired effect.

2021-11-22 13:57 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/ffs_map.v
> +    latchsre _TECHMAP_REPLACE_ (.D(D), .Q(Q), .E(1'b1), .G(E),  .R(!R), .S(!S));
I believe that it should be `.E(E)`

2021-11-22 13:57 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/ffs_map.v
> +    latchnsre _TECHMAP_REPLACE_ (.D(D), .Q(Q), .E(1'b1), .G(E),  .R(!R), .S(!S));
and here I believe that it should be `.E(E)` here as well provided that `latchnsre` inverts the signal internally.

2021-11-22 13:57 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +endmodule
I believe that neither of those cells are part of the `qlf_k6n10f` architecture. I suggest removing them.

2021-11-22 13:57 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +*/
Remove commented code

2021-11-22 13:57 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +*/
Remove commented code

2021-11-22 15:39 UTC, tpagarani commented on ql-qlf-plugin/qlf_k6n10f/ffs_map.v
> +    latchsre _TECHMAP_REPLACE_ (.D(D), .Q(Q), .E(1'b1), .G(E),  .R(!R), .S(!S));
For the latch Enable is supposed to be connected to Gate (G)

2021-11-22 16:45 UTC, tpagarani commented on ql-qlf-plugin/qlf_k6n10f/ffs_map.v
> +    latchnsre _TECHMAP_REPLACE_ (.D(D), .Q(Q), .E(1'b1), .G(E),  .R(!R), .S(!S));
Same as above latch enable pin is G.

2021-11-23 08:16 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/ffs_map.v
> +    latchsre _TECHMAP_REPLACE_ (.D(D), .Q(Q), .E(1'b1), .G(E),  .R(!R), .S(!S));
Ok, makes sense.

2021-11-23 08:16 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/ffs_map.v
> +    latchnsre _TECHMAP_REPLACE_ (.D(D), .Q(Q), .E(1'b1), .G(E),  .R(!R), .S(!S));
Alright, same as above.

2021-11-23 10:17 UTC, tpagarani commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +endmodule
removed

2021-11-23 10:17 UTC, tpagarani commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +*/
removed

2021-11-23 10:17 UTC, tpagarani commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +*/
removed

2021-11-23 10:18 UTC, tpagarani commented
@mkurc-ant, i have taken care of review comments from you as well as updated the tests for k6n10f. Kindly review and merge.

2021-11-23 11:04 UTC, mkurc-ant approved these changes
ok, LGTM

2021-11-23 11:04 UTC, merged