Add plugin to integrate inverters with invertable pins
SymbiFlow/yosys-symbiflow-plugins pull request #55
Opened 2020-11-24 15:55 UTC by tmichalak

This plugins integrates inverters with invertible pins (pins with invertible attribute set).
So in case there is an inverter driving a pin with `invertible_pin` attribute set to name of the parameter we want to toggle, the inverter is being removed and the value of the attribute toggled. 
It can be used to absorb the inverter on a clock input (for example ISERDES's CLKB) and toggling the IS_CLKB_INVERTED attribute.

2020-11-24 18:14 UTC, mithro commented
I would call this "inverter absorption" but it seems that upstream Yosys calls this "merging". See the ["C.79 memory_dff – merge input/output DFFs into memories"](http://www.clifford.at/yosys/cmd_memory_dff.html) command for example.

The opposite of that command seems to be ["C.82 memory_nordff – extract read port FFs from memories"](http://www.clifford.at/yosys/cmd_memory_nordff.html).

It would have been better if that above example was something like `memory_merge_dff` and `memory_extract_dff`...

I would name this `pin_merge_inv` and make sure there is an `pin_extract_inv` which does the opposite.

2020-11-24 18:15 UTC, mithro commented on integrateinv-plugin/integrateinv.cc
> +    log("of a parameter controlling the inversion. Whenever an inverter\n");
Same line twice?

2020-11-24 18:22 UTC, tmichalak commented on integrateinv-plugin/integrateinv.cc
> +    log("of a parameter controlling the inversion. Whenever an inverter\n");
Fixed.

2020-11-30 17:20 UTC, litghost requested changes
CI is red?

2020-12-01 16:10 UTC, tmichalak commented
> CI is red?

Rebased, it's green now

2020-12-01 18:33 UTC, merged